name: star-wars-api-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: build and test
        run: |
         docker run --rm -v "${{ github.workspace }}:/home/gradle/project" -w /home/gradle/project gradle:jdk15-hotspot gradle test
      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results/

         
          
