name: star-wars-api-tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: addnab/docker-run-action@v2
        with:
         image: gradle:jdk15-hotspot
         options: -v ${{ github.workspace }}:/home/gradle/project
         run: |
          --rm -u gradle -w /home/gradle/project gradle gradle test
 
         
          
